language: python

addons:
  apt:
    packages:
      - python3-dev
      - fluid-soundfont-gm

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - make test
  - make coverage_data

after_success: coveralls

cache: pip
